import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'; // Toasterをインポート
import AdminBar from "@/components/common/AdminBar";
import Header from '@/components/common/Header'; // ★NavBarをインポート
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} !pt-24`}>
        <Header />
        {children}
        <Toaster richColors position="top-center" />
        <AdminBar />
      </body>
    </html>
  );
}
